### ISSUE TITLE
class not found

### ISSUE THREAD

**Issue by the-sumit-agrawal** [DWorkS/VolleyPlus#84]
2018-12-26 13:13:49.156 26069-26098/tech.profusion.sumit.multiparttest E/AndroidRuntime: FATAL EXCEPTION: Thread-5
    Process: tech.profusion.sumit.locationclient, PID: 26069
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
        at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:151)
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:97)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:118)
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:151) 
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:97) 
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:118) 
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/tech.profusion.sumit.locationclient-3L3s5b3Q9nBd1F9tzkClXw==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:727)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:810)
        at android.app.LoadedApk.getResources(LoadedApk.java:1032)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5749)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
2018-12-26 13:13:49.158 26069-26098/tech.profusion.sumit.locationclient E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by the-sumit-agrawal** [comment]
My code was working with com.android.volley:volley:1.1.1 but after switching to volley plus application started crashing. 
So, I added <uses-library android:name="org.apache.http.legacy" android:required="false" /> to my manifest for library support app stopped crashing but request not being sent to server.
