### ISSUE TITLE
volley plus is giving no such method error in android 11 in java

### ISSUE THREAD

**Issue by Orgdevelopers** [DWorkS/VolleyPlus#90]
this is stack trace

Build version: 1.1 
Build date: 1981-01-01 01:01:02 
Current date: 2021-11-01 11:19:45 
Device: Realme RMX2151 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.NoSuchMethodError: no static method "Lcom/volley/plus/VPackages/Methods;.clearCache(Landroid/content/Context;)V"
	at com.volley.plus.VPackages.ConfigureVolley.initalizeSdk(Native Method)
	at com.volley.plus.VPackages.ConfigureVolley.access$000(ConfigureVolley.java:17)
	at com.volley.plus.VPackages.ConfigureVolley$1.onResponse(ConfigureVolley.java:48)
	at com.volley.plus.VPackages.ConfigureVolley$1.onResponse(ConfigureVolley.java:40)
	at com.android.volley.request.JsonRequest.deliverResponse(JsonRequest.java:66)
	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:255)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

User actions: 
2021-11-01 11:16:44: SplashA created
2021-11-01 11:16:44: SplashA resumed

**Comment by Sukhmanderis** [comment]
yes i am facing this problem too is anyone have any solution please help me too

**Comment by AdnanAliShabir** [comment]
I'm also facing this error, any solution for this error?

**Comment by mrinmay07** [comment]
Use 
implementation 'com.android.volley:volley:1.2.1'

**Comment by mrinmay07** [comment]
> yes i am facing this problem too is anyone have any solution please help me

Use

> this is stack trace
> 
> Build version: 1.1 Build date: 1981-01-01 01:01:02 Current date: 2021-11-01 11:19:45 Device: Realme RMX2151 OS version: Android 11 (SDK 30)
> 
> Stack trace: java.lang.NoSuchMethodError: no static method "Lcom/volley/plus/VPackages/Methods;.clearCache(Landroid/content/Context;)V" at com.volley.plus.VPackages.ConfigureVolley.initalizeSdk(Native Method) at com.volley.plus.VPackages.ConfigureVolley.access$000(ConfigureVolley.java:17) at com.volley.plus.VPackages.ConfigureVolley$1.onResponse(ConfigureVolley.java:48) at com.volley.plus.VPackages.ConfigureVolley$1.onResponse(ConfigureVolley.java:40) at com.android.volley.request.JsonRequest.deliverResponse(JsonRequest.java:66) at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:255) at android.app.ActivityThread.main(ActivityThread.java:8212) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
> 
> User actions: 2021-11-01 11:16:44: SplashA created 2021-11-01 11:16:44: SplashA resumed

--------------------------------------------------------------------------------------------------------------
Use
implementation 'com.android.volley:volley:1.2.1'

**Comment by mrinmay07** [comment]
I'm also facing this problem. But using this "implementation 'com.android.volley:volley:1.2.1' ", my problem solved.
